CREATE TABLE IF NOT EXISTS COMPANY(
  ID INT PRIMARY KEY NOT NULL,
  NAME TEXT,
  AGE INTEGER,
  SALARY REAL,
  JOB TEXT
);
INSERT INTO COMPANY(ID, NAME, AGE, SALARY, JOB) VALUES
(1, 'DIANA', 20, 15000.00, 'CEO'),
(2, 'AMANDA', 25, 1200.00, 'MANAGER'),
(3, 'jamie', 26, 1300.00, 'senior MANAGER');

SELECT * FROM COMPANY;
SELECT MAX(SALARY) FROM COMPANY;
SELECT MIN(SALARY)FROM COMPANY;
SELECT SUM(SALARY)FROM COMPANY;